qfile='/depot/exam/dcx_scratch/qfiles/2018_exam1_gonzalez.txt'
course='AST-1002' # course code
section='5008' # section number
semester='Fall'
year='2018'
periods='MWF 5'
instructor='Prof. Anthony Gonzalez'
examdate='Sep 24th' # exam date
examnum='1' # exam number
testform='A' # test form code on scantron
timelimit='50' # time limit in minutes
page1='/depot/exam/dcx_scratch/pages/anthony_1stPageBody.txt'
page2='/depot/exam/dcx_scratch/pages/2ndPageBody.txt'
mode='proof' # PROOF,EXAM,GRADE
mode='exam'
num_exam='175' # number of total exams to print, including those for disabled
num_disabled='1' # number of disabled students
