qfile='/depot/exam/dcx_scratch/qfiles/Ast2037_Fall2018_1.txt'
course='AST-2037' # course code
section='1021' # section number
semester='Fall'
year='2018'
periods='MWF 4'
instructor='Dr. Naibi Marinas'
examdate='Sep 21st' # exam date
examnum='1' # exam number
testform='A' # test form code on scantron
timelimit='50' # time limit in minutes
page1='/depot/exam/dcx_scratch/pages/1stPageBody.txt'
page2='/depot/exam/dcx_scratch/pages/2ndPageBody.txt'
mode='proof' # PROOF,EXAM,GRADE
num_exam='85' # number of total exams to print, including those for disabled
num_disabled='1' # number of disabled students
