qfile        = pexampath + 'qfiles/EXAM_EXAMPLE.txt' # question file
course       = 'AST-2037' # course code
section      = '1021' # section number
semester     = 'Fall' # 'Fall'/'Spring'/'Summer'/'Summer A'/'Summer B'
year         = '2020'
periods      = 'MWF 4' # lecture schedule
instructor   = 'Dr. Naibi Marinas'
examdate     = 'Sep 21st' # exam date
examnum      = '1' # exam number
testform     = 'A' # test form code on scantron
timelimit    = '50' # exam time limit in minutes
page1        = pexampath + 'pages/1stPageBody.txt' # first page of the exam
page2        = pexampath + 'pages/2ndPageBody.txt' # second page of the exam
mode         = 'proof' # 'PROOF'/'EXAM'
num_exam     = '85' # number of total exams to print, including those for disabled
num_disabled = '1' # number of students going to Disability Resource Center
