qfile='/depot/exam/dcx_scratch/qfiles/Ast3043_Exam1_F2018.txt'
course='AST-3043' # course code
section='215G' # section number
semester='Fall'
year='2018'
periods='MWF 6'
instructor='Dr. Naibi Marinas'
examdate='Sep 28th' # exam date
examnum='1' # exam number
testform='A' # test form code on scantron
timelimit='50' # time limit in minutes
page1='/depot/exam/dcx_scratch/pages/naibi_1stPageBody.txt'
page2='/depot/exam/dcx_scratch/pages/2ndPageBody.txt'
mode='proof' # PROOF,EXAM,GRADE
mode='exam'
num_exam='65' # number of total exams to print, including those for disabled
num_disabled='0' # number of disabled students
